services:
  backend:
    build: ./backend
    volumes:
      - ./backend:/workdir
    ports:
      - 8000:8000
  frontend:
    build: ./frontend
    volumes:
      - ./frontend:/workdir
    ports:
      - 3000:3000