services:
  backend:
    build: ./backend
    volumes:
      - ./backend:/workdir
    ports:
      - 8000:8000
  frontend:
    build: ./frontend
    volumes:
      - ./frontend:/workdir
    ports:
      - 3010:3000
  db:
    image: mysql:8.3
    volumes:
      - ./backend/laravel_poker/mysql_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: dev
    ports:
      - 3306:3306